#!/bin/bash
COLOR="\x1B[0;32m"
NO_COLOR="\x1B[0m"
case $1 in
  play)
    if pgrep -x "spotify" > /dev/null
    then
      dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify\
                /org/mpris/MediaPlayer2\
                org.mpris.MediaPlayer2.Player.Play > /dev/null
    fi
  ;;
  pause)
    if pgrep -x "spotify" > /dev/null
    then
      dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify\
                /org/mpris/MediaPlayer2\
                org.mpris.MediaPlayer2.Player.Pause > /dev/null
    fi
  ;;
  play-pause|toggle)
    if pgrep -x "spotify" > /dev/null
    then
      dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify\
                /org/mpris/MediaPlayer2\
                org.mpris.MediaPlayer2.Player.PlayPause > /dev/null
    else
      spotify
    fi
  ;;
  next)
    if pgrep -x "spotify" > /dev/null
    then
      dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify\
                /org/mpris/MediaPlayer2\
                org.mpris.MediaPlayer2.Player.Next > /dev/null
    fi
  ;;
  prev)
    if pgrep -x "spotify" > /dev/null
    then
      dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify\
                /org/mpris/MediaPlayer2\
                org.mpris.MediaPlayer2.Player.Previous > /dev/null
    fi
  ;;
  open)
    if ! pgrep -x "spotify" > /dev/null
    then
      spotify
    fi
  ;;
  version)
    echo '0.0.1'
  ;;
  install)
    if [ $EUID != 0 ]; then
      sudo "$0" "$@"
      exit $?
    fi

    if lsb_release -ds | grep "Ubuntu" > /dev/null
    then
      if [[ $2 != '--simulate' ]] && which spotify > /dev/null
      then
        echo -e "${COLOR}Spotify${NO_COLOR} is already installed"
      else
        echo "This is going to install Spotify following these instructions:"
        echo -e "${COLOR}https://www.spotify.com/es/download/linux/${NO_COLOR}"
        read -p "Do you wanna continue?" -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
          if [[ $2 != '--simulate' ]]
          then
            # As seen in: https://www.spotify.com/es/download/linux/
            # 1. Add the Spotify repository signing key to be able to verify downloaded packages
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886

            # 2. Add the Spotify repository
            echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

            # 3. Update list of available packages
            apt-get update

            # 4. Install Spotify
            apt-get install spotify-client
          else
            echo -e "Simulated ${COLOR}Spotify${NO_COLOR} installation, nothing happened"
          fi
        else
          echo -e "${COLOR}Spotify${NO_COLOR} installation skipped"
        fi
      fi

      if [[ $2 != '--simulate' ]] && which spotty > /dev/null
      then
        echo -e "${COLOR}Spotty${NO_COLOR} is already installed"
      else
        echo "This is going to install Spotty following these instructions:"
        echo -e "${COLOR}https://www.spotify.com/es/download/linux/${NO_COLOR}"
        read -p "Do you wanna continue?" -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
          if [[ $2 != '--simulate' ]]
          then
            cp spotty /usr/local/bin/spotty
          else
            echo -e "Simulated ${COLOR}Spotty${NO_COLOR} installation, nothing happened"
          fi
        else
          echo -e "${COLOR}Spotty${NO_COLOR} installation skipped"
        fi
      fi

    else
      echo -e "Use: ${COLOR}https://www.spotify.com/es/download/linux/${NO_COLOR}"
    fi
  ;;
  web|go)
    xdg-open https://www.spotify.com/es/download/linux/
  ;;
esac

